displayName=Minigame Attack Styles
author=Rosters
description=Enable warned attack styles within minigames with disabled exp drops.
tags=minigames
plugins=com.minigameAttackStyles.MinigameAttackStylesPlugin